services:
########## NGINX ##########
  nginx:
    build:
      context: ${NGINX_CONTAINER_PATH}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
      - ${HOST_VOLUMES_PATH}/nginx/logs:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    links:
      - php-fpm

########## PHP-FPM ##########
  php-fpm:
    build:
      context: ${PHP_FPM_CONTAINER_PATH}
      args:
        - PHP_VERSION=${PHP_VERSION}
    volumes:
      - ${PHP_FPM_CONTAINER_PATH}/php.ini:/usr/local/etc/php/php.ini
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}

  php-fpm7:
    build:
      context: ${PHP_FPM_CONTAINER_PATH}
      args:
        - PHP_VERSION=7.4
    volumes:
      - ${PHP_FPM_CONTAINER_PATH}/php.ini:/usr/local/etc/php/php.ini
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}

########## WORKSPACE ##########
  workspace:
    build:
      context: ${WORKSPACE_CONTAINER_PATH}
      args:
        - PHP_VERSION=${PHP_VERSION}
        - TZ=${WORKSPACE_TIMEZONE}
        - LOCALE=${WORKSPACE_LOCALE}
        - PUNAME=${WORKSPACE_NONROOT_USER_NAME}
        - PUID=${WORKSPACE_NONROOT_USER_ID}
        - PGNAME=${WORKSPACE_NONROOT_GROUP_NAME}
        - PGID=${WORKSPACE_NONROOT_GROUP_ID}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
    tty: true
  
  workspace7:
    build:
      context: ${WORKSPACE_CONTAINER_PATH}
      args:
        - PHP_VERSION=7.4
        - TZ=${WORKSPACE_TIMEZONE}
        - LOCALE=${WORKSPACE_LOCALE}
        - PUNAME=${WORKSPACE_NONROOT_USER_NAME}
        - PUID=${WORKSPACE_NONROOT_USER_ID}
        - PGNAME=${WORKSPACE_NONROOT_GROUP_NAME}
        - PGID=${WORKSPACE_NONROOT_GROUP_ID}
    volumes:
      - ${HOST_CODE_PATH}:${CONTAINER_CODE_PATH}
    tty: true

########## POSTGRES ##########
  postgres:
    user: root
    image: postgis/postgis:10-2.5
    shm_size: 4g
    volumes:
      - ${HOST_VOLUMES_PATH}/postgres:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}

########## PGADMIN ##########
  pgadmin:
    user: root
    image: dpage/pgadmin4:latest
    volumes:
      - ${HOST_VOLUMES_PATH}/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT}:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_PASSWORD}

########## GEOSERVER ##########
  geoserver:
    build:
      context: ${GEOSERVER_CONTAINER_PATH}
    volumes:
      - ${HOST_VOLUMES_PATH}/geoserver:${GEOSERVER_DATA_DIR}
    ports:
      - ${GEOSERVER_PORT}:8080
